server:
  port: 5000
  host: '0.0.0.0'
emcc:
    path: '/usr/local/bin/emcc'
    option: '-O1 -W -Wall -Qunused-arguments'
    env: ''
out:
    path: '/tmp/'
mongo:
    host: 'localhost'
    database: 'aspen'
